CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    migration_id character varying(150) NOT NULL,
    product_version character varying(32) NOT NULL,
    CONSTRAINT pk___ef_migrations_history PRIMARY KEY (migration_id)
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20251111145800_InitialCreate') THEN
    CREATE TABLE business_settings (
        id smallint GENERATED BY DEFAULT AS IDENTITY,
        name character varying(160) NOT NULL,
        banner_title character varying(160),
        banner_subtitle character varying(200),
        phone_wa character varying(40),
        address character varying(200),
        instagram character varying(160),
        facebook character varying(160),
        tiktok character varying(160),
        opening_hours text,
        created_at timestamp with time zone NOT NULL,
        updated_at timestamp with time zone NOT NULL,
        CONSTRAINT pk_business_settings PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20251111145800_InitialCreate') THEN
    CREATE TABLE categories (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        name character varying(120) NOT NULL,
        slug character varying(140) NOT NULL,
        is_visible boolean NOT NULL,
        sort_order integer NOT NULL,
        created_at timestamp with time zone NOT NULL,
        updated_at timestamp with time zone NOT NULL,
        CONSTRAINT pk_categories PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20251111145800_InitialCreate') THEN
    CREATE TABLE "user" (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        usuario character varying(150) NOT NULL,
        password character varying(150) NOT NULL,
        rol character varying(150) NOT NULL,
        CONSTRAINT pk_user PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20251111145800_InitialCreate') THEN
    CREATE TABLE products (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        category_id integer NOT NULL,
        name character varying(160) NOT NULL,
        slug character varying(180) NOT NULL,
        description text,
        priceCents integer NOT NULL,
        is_visible boolean NOT NULL,
        created_at timestamp with time zone NOT NULL,
        updated_at timestamp with time zone NOT NULL,
        CONSTRAINT pk_products PRIMARY KEY (id),
        CONSTRAINT fk_products_categories_category_id FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20251111145800_InitialCreate') THEN
    CREATE INDEX ix_categories_is_visible_sort_order ON categories (is_visible, sort_order);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20251111145800_InitialCreate') THEN
    CREATE INDEX ix_products_category_id_is_visible ON products (category_id, is_visible);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20251111145800_InitialCreate') THEN
    CREATE INDEX ix_products_name ON products USING gin (name);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20251111145800_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20251111145800_InitialCreate', '8.0.10');
    END IF;
END $EF$;
COMMIT;

