// <auto-generated />
using System;
using Back.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Back.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Back.Models.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("action");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<int?>("ByUser")
                        .HasColumnType("integer")
                        .HasColumnName("by_user");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("entity");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("entity_id");

                    b.Property<string>("Meta")
                        .HasColumnType("text")
                        .HasColumnName("meta");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("Entity", "EntityId")
                        .HasDatabaseName("ix_audit_logs_entity_entity_id");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("Back.Models.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("address");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("phone");

                    b.Property<string>("WaNumber")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("wa_number");

                    b.HasKey("Id")
                        .HasName("pk_branches");

                    b.ToTable("branches", (string)null);
                });

            modelBuilder.Entity("Back.Models.BusinessSettings", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("address");

                    b.Property<DateTime?>("BannerImageUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("banner_image_updated_at");

                    b.Property<byte[]>("BannerImageWebp")
                        .HasColumnType("bytea")
                        .HasColumnName("banner_image_webp");

                    b.Property<string>("BannerSubtitle")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("banner_subtitle");

                    b.Property<string>("BannerTitle")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("banner_title");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("description");

                    b.Property<string>("Facebook")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("facebook");

                    b.Property<string>("Instagram")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("instagram");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<string>("OpeningHours")
                        .HasColumnType("jsonb")
                        .HasColumnName("opening_hours");

                    b.Property<string>("PhoneWa")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("phone_wa");

                    b.Property<string>("Tiktok")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("tiktok");

                    b.Property<string>("TransferAlias")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("transfer_alias");

                    b.HasKey("Id")
                        .HasName("pk_business_settings");

                    b.ToTable("business_settings", (string)null);
                });

            modelBuilder.Entity("Back.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DefaultStation")
                        .HasColumnType("text")
                        .HasColumnName("default_station");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasIndex("SortOrder")
                        .HasDatabaseName("ix_categories_sort_order");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("Back.Models.Combo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<int>("priceCents")
                        .HasColumnType("integer")
                        .HasColumnName("price_cents");

                    b.HasKey("Id")
                        .HasName("pk_combos");

                    b.ToTable("combos", (string)null);
                });

            modelBuilder.Entity("Back.Models.ComboItem", b =>
                {
                    b.Property<int>("ComboId")
                        .HasColumnType("integer")
                        .HasColumnName("combo_id");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<int>("Qty")
                        .HasColumnType("integer")
                        .HasColumnName("qty");

                    b.HasKey("ComboId", "ProductId")
                        .HasName("pk_combo_items");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_combo_items_product_id");

                    b.ToTable("combo_items", (string)null);
                });

            modelBuilder.Entity("Back.Models.Coupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int?>("MinTotalCents")
                        .HasColumnType("integer")
                        .HasColumnName("min_total_cents");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("type");

                    b.Property<int?>("UsageLimit")
                        .HasColumnType("integer")
                        .HasColumnName("usage_limit");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTimeOffset>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_to");

                    b.Property<int>("Value")
                        .HasColumnType("integer")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_coupons");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_coupons_code");

                    b.ToTable("coupons", (string)null);
                });

            modelBuilder.Entity("Back.Models.CouponRedemption", b =>
                {
                    b.Property<int>("CouponId")
                        .HasColumnType("integer")
                        .HasColumnName("coupon_id");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer")
                        .HasColumnName("order_id");

                    b.HasKey("CouponId", "OrderId")
                        .HasName("pk_coupon_redemptions");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_coupon_redemptions_order_id");

                    b.ToTable("coupon_redemptions", (string)null);
                });

            modelBuilder.Entity("Back.Models.GrowthSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<bool>("DynamicPricingEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("dynamic_pricing_enabled");

                    b.Property<int>("DynamicPricingOffPeakDiscount")
                        .HasColumnType("integer")
                        .HasColumnName("dynamic_pricing_off_peak_discount");

                    b.Property<string>("DynamicPricingOffPeakEnd")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("dynamic_pricing_off_peak_end");

                    b.Property<string>("DynamicPricingOffPeakStart")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("dynamic_pricing_off_peak_start");

                    b.Property<string>("DynamicPricingPeakMessage")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("dynamic_pricing_peak_message");

                    b.Property<string>("DynamicPricingProductIdsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("dynamic_pricing_product_ids_json");

                    b.Property<string>("HappyHourDaysJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("happy_hour_days_json");

                    b.Property<int>("HappyHourDiscount")
                        .HasColumnType("integer")
                        .HasColumnName("happy_hour_discount");

                    b.Property<bool>("HappyHourEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("happy_hour_enabled");

                    b.Property<string>("HappyHourEnd")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("happy_hour_end");

                    b.Property<string>("HappyHourProductIdsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("happy_hour_product_ids_json");

                    b.Property<string>("HappyHourStart")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("happy_hour_start");

                    b.Property<bool>("PeakHourBoostFastProducts")
                        .HasColumnType("boolean")
                        .HasColumnName("peak_hour_boost_fast_products");

                    b.Property<bool>("PeakHourEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("peak_hour_enabled");

                    b.Property<string>("PeakHourEnd")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("peak_hour_end");

                    b.Property<bool>("PeakHourHideSlowProducts")
                        .HasColumnType("boolean")
                        .HasColumnName("peak_hour_hide_slow_products");

                    b.Property<string>("PeakHourStart")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("peak_hour_start");

                    b.Property<int>("PeakHourThresholdOrders")
                        .HasColumnType("integer")
                        .HasColumnName("peak_hour_threshold_orders");

                    b.Property<bool>("SmartCombosComboForTwo")
                        .HasColumnType("boolean")
                        .HasColumnName("smart_combos_combo_for_two");

                    b.Property<bool>("SmartCombosMostRequested")
                        .HasColumnType("boolean")
                        .HasColumnName("smart_combos_most_requested");

                    b.Property<bool>("SmartCombosNightCombo")
                        .HasColumnType("boolean")
                        .HasColumnName("smart_combos_night_combo");

                    b.Property<string>("TwoForOneDaysJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("two_for_one_days_json");

                    b.Property<bool>("TwoForOneEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_for_one_enabled");

                    b.Property<string>("TwoForOneProductIdsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("two_for_one_product_ids_json");

                    b.Property<int>("UpsellDiscount")
                        .HasColumnType("integer")
                        .HasColumnName("upsell_discount");

                    b.Property<bool>("UpsellEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("upsell_enabled");

                    b.Property<string>("UpsellMessage")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("upsell_message");

                    b.Property<string>("UpsellProductIdsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("upsell_product_ids_json");

                    b.Property<int>("WinbackDays")
                        .HasColumnType("integer")
                        .HasColumnName("winback_days");

                    b.Property<bool>("WinbackEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("winback_enabled");

                    b.HasKey("Id")
                        .HasName("pk_growth_settings");

                    b.ToTable("growth_settings", (string)null);
                });

            modelBuilder.Entity("Back.Models.KitchenTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedToUserId")
                        .HasColumnType("integer")
                        .HasColumnName("assigned_to_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at");

                    b.Property<string>("ItemsSnapshot")
                        .HasColumnType("jsonb")
                        .HasColumnName("items_snapshot");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer")
                        .HasColumnName("order_id");

                    b.Property<DateTimeOffset?>("ReadyAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ready_at");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Station")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("station");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("TicketNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ticket_number");

                    b.HasKey("Id")
                        .HasName("pk_kitchen_tickets");

                    b.HasIndex("AssignedToUserId")
                        .HasDatabaseName("ix_kitchen_tickets_assigned_to_user_id");

                    b.HasIndex("TicketNumber")
                        .HasDatabaseName("ix_kitchen_tickets_ticket_number");

                    b.HasIndex("OrderId", "Station")
                        .HasDatabaseName("ix_kitchen_tickets_order_id_station");

                    b.HasIndex("Status", "Station")
                        .HasDatabaseName("ix_kitchen_tickets_status_station");

                    b.ToTable("kitchen_tickets", (string)null);
                });

            modelBuilder.Entity("Back.Models.Modifier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<int>("PriceCentsDelta")
                        .HasColumnType("integer")
                        .HasColumnName("price_cents_delta");

                    b.HasKey("Id")
                        .HasName("pk_modifiers");

                    b.ToTable("modifiers", (string)null);
                });

            modelBuilder.Entity("Back.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("address");

                    b.Property<int?>("BranchId")
                        .HasColumnType("integer")
                        .HasColumnName("branch_id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("channel");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("customer_name");

                    b.Property<int>("DiscountCents")
                        .HasColumnType("integer")
                        .HasColumnName("discount_cents");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("phone");

                    b.Property<string>("PublicCode")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("public_code");

                    b.Property<string>("Reference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("reference");

                    b.Property<DateTimeOffset?>("ScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("SubtotalCents")
                        .HasColumnType("integer")
                        .HasColumnName("subtotal_cents");

                    b.Property<int?>("TableSessionId")
                        .HasColumnType("integer")
                        .HasColumnName("table_session_id");

                    b.Property<string>("TakeMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("take_mode");

                    b.Property<int>("TipCents")
                        .HasColumnType("integer")
                        .HasColumnName("tip_cents");

                    b.Property<int>("TotalCents")
                        .HasColumnType("integer")
                        .HasColumnName("total_cents");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_orders");

                    b.HasIndex("BranchId")
                        .HasDatabaseName("ix_orders_branch_id");

                    b.HasIndex("PublicCode")
                        .IsUnique()
                        .HasDatabaseName("ix_orders_public_code");

                    b.HasIndex("TableSessionId")
                        .HasDatabaseName("ix_orders_table_session_id");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("Back.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("LineTotalCents")
                        .HasColumnType("integer")
                        .HasColumnName("line_total_cents");

                    b.Property<string>("ModifiersSnapshot")
                        .HasColumnType("jsonb")
                        .HasColumnName("modifiers_snapshot");

                    b.Property<int>("ModifiersTotalCents")
                        .HasColumnType("integer")
                        .HasColumnName("modifiers_total_cents");

                    b.Property<string>("NameSnapshot")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name_snapshot");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer")
                        .HasColumnName("order_id");

                    b.Property<int?>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<int>("Qty")
                        .HasColumnType("integer")
                        .HasColumnName("qty");

                    b.Property<int>("UnitPriceCents")
                        .HasColumnType("integer")
                        .HasColumnName("unit_price_cents");

                    b.HasKey("Id")
                        .HasName("pk_order_items");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_order_items_order_id");

                    b.ToTable("order_items", (string)null);
                });

            modelBuilder.Entity("Back.Models.OrderStatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Estado")
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.HasKey("Id")
                        .HasName("pk_orderstatus");

                    b.HasIndex("Id", "Activo")
                        .HasDatabaseName("ix_orderstatus_id_activo");

                    b.ToTable("orderstatus", (string)null);
                });

            modelBuilder.Entity("Back.Models.OrderStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<int?>("ChangedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("changed_by_user_id");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer")
                        .HasColumnName("order_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_order_status_history");

                    b.HasIndex("ChangedByUserId")
                        .HasDatabaseName("ix_order_status_history_changed_by_user_id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_order_status_history_order_id");

                    b.ToTable("order_status_history", (string)null);
                });

            modelBuilder.Entity("Back.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("DiscountDoublePriceCents")
                        .HasColumnType("integer")
                        .HasColumnName("discount_double_price");

                    b.Property<int?>("DiscountPriceCents")
                        .HasColumnType("integer")
                        .HasColumnName("discount_price");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<int?>("DoublePriceCents")
                        .HasColumnType("integer")
                        .HasColumnName("double_price_cents");

                    b.Property<byte[]>("ImageData")
                        .HasColumnType("bytea")
                        .HasColumnName("image_data");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<int>("PriceCents")
                        .HasColumnType("integer")
                        .HasColumnName("price");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_products_category_id");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_products_name");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Name"), "gin");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("Back.Models.ProductModifier", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<int>("ModifierId")
                        .HasColumnType("integer")
                        .HasColumnName("modifier_id");

                    b.HasKey("ProductId", "ModifierId")
                        .HasName("pk_product_modifiers");

                    b.HasIndex("ModifierId")
                        .HasDatabaseName("ix_product_modifiers_modifier_id");

                    b.ToTable("product_modifiers", (string)null);
                });

            modelBuilder.Entity("Back.Models.Table", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("integer")
                        .HasColumnName("branch_id");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_tables");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_tables_status");

                    b.HasIndex("BranchId", "SortOrder")
                        .HasDatabaseName("ix_tables_branch_id_sort_order");

                    b.ToTable("tables", (string)null);
                });

            modelBuilder.Entity("Back.Models.TableSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<int?>("ClosedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("closed_by_user_id");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("customer_name");

                    b.Property<int>("GuestCount")
                        .HasColumnType("integer")
                        .HasColumnName("guest_count");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_at");

                    b.Property<int?>("OpenedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("opened_by_user_id");

                    b.Property<int?>("AssignedWaiterId")
                        .HasColumnType("integer")
                        .HasColumnName("assigned_waiter_id");

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("payment_method");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("SubtotalCents")
                        .HasColumnType("integer")
                        .HasColumnName("subtotal_cents");

                    b.Property<int>("TableId")
                        .HasColumnType("integer")
                        .HasColumnName("table_id");

                    b.Property<int>("TipCents")
                        .HasColumnType("integer")
                        .HasColumnName("tip_cents");

                    b.Property<int>("TotalCents")
                        .HasColumnType("integer")
                        .HasColumnName("total_cents");

                    b.HasKey("Id")
                        .HasName("pk_table_sessions");

                    b.HasIndex("ClosedByUserId")
                        .HasDatabaseName("ix_table_sessions_closed_by_user_id");

                    b.HasIndex("OpenedByUserId")
                        .HasDatabaseName("ix_table_sessions_opened_by_user_id");

                    b.HasIndex("AssignedWaiterId")
                        .HasDatabaseName("ix_table_sessions_assigned_waiter_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_table_sessions_status");

                    b.HasIndex("TableId")
                        .IsUnique()
                        .HasDatabaseName("ix_table_sessions_table_id")
                        .HasFilter("closed_at IS NULL");

                    b.HasIndex("TableId", "ClosedAt")
                        .HasDatabaseName("ix_table_sessions_table_id_closed_at");

                    b.ToTable("table_sessions", (string)null);
                });

            modelBuilder.Entity("Back.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("password");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("rol");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("usuario");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone");

                    b.Property<string>("TelegramChatId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("telegram_chat_id");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("Back.Models.UserPushSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("auth");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("endpoint");

                    b.Property<string>("P256dh")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("p256dh");

                    b.Property<string>("Station")
                        .HasColumnType("text")
                        .HasColumnName("station");

                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_push_subscriptions");

                    b.HasIndex("Endpoint")
                        .IsUnique()
                        .HasDatabaseName("ix_user_push_subscriptions_endpoint");

                    b.ToTable("user_push_subscriptions", (string)null);
                });

            modelBuilder.Entity("Back.Models.ComboItem", b =>
                {
                    b.HasOne("Back.Models.Combo", "Combo")
                        .WithMany("Items")
                        .HasForeignKey("ComboId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_combo_items_combos_combo_id");

                    b.HasOne("Back.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_combo_items_products_product_id");

                    b.Navigation("Combo");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Back.Models.CouponRedemption", b =>
                {
                    b.HasOne("Back.Models.Coupon", "Coupon")
                        .WithMany("Redemptions")
                        .HasForeignKey("CouponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_coupon_redemptions_coupons_coupon_id");

                    b.HasOne("Back.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_coupon_redemptions_orders_order_id");

                    b.Navigation("Coupon");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Back.Models.KitchenTicket", b =>
                {
                    b.HasOne("Back.Models.User", "AssignedToUser")
                        .WithMany()
                        .HasForeignKey("AssignedToUserId")
                        .HasConstraintName("fk_kitchen_tickets_user_assigned_to_user_id");

                    b.HasOne("Back.Models.Order", "Order")
                        .WithMany("KitchenTickets")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_kitchen_tickets_orders_order_id");

                    b.Navigation("AssignedToUser");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Back.Models.Order", b =>
                {
                    b.HasOne("Back.Models.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .HasConstraintName("fk_orders_branches_branch_id");

                    b.HasOne("Back.Models.TableSession", "TableSession")
                        .WithMany("Orders")
                        .HasForeignKey("TableSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_orders_table_sessions_table_session_id");

                    b.Navigation("Branch");

                    b.Navigation("TableSession");
                });

            modelBuilder.Entity("Back.Models.OrderItem", b =>
                {
                    b.HasOne("Back.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_items_orders_order_id");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Back.Models.OrderStatusHistory", b =>
                {
                    b.HasOne("Back.Models.User", "ChangedBy")
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .HasConstraintName("fk_order_status_history_user_changed_by_user_id");

                    b.HasOne("Back.Models.Order", "Order")
                        .WithMany("StatusHistory")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_status_history_orders_order_id");

                    b.Navigation("ChangedBy");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Back.Models.Product", b =>
                {
                    b.HasOne("Back.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_products_categories_category_id");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Back.Models.ProductModifier", b =>
                {
                    b.HasOne("Back.Models.Modifier", "Modifier")
                        .WithMany("ProductModifiers")
                        .HasForeignKey("ModifierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_modifiers_modifiers_modifier_id");

                    b.HasOne("Back.Models.Product", "Product")
                        .WithMany("ProductModifiers")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_modifiers_products_product_id");

                    b.Navigation("Modifier");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Back.Models.Table", b =>
                {
                    b.HasOne("Back.Models.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tables_branches_branch_id");

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("Back.Models.TableSession", b =>
                {
                    b.HasOne("Back.Models.User", "ClosedByUser")
                        .WithMany()
                        .HasForeignKey("ClosedByUserId")
                        .HasConstraintName("fk_table_sessions_user_closed_by_user_id");

                    b.HasOne("Back.Models.User", "OpenedByUser")
                        .WithMany()
                        .HasForeignKey("OpenedByUserId")
                        .HasConstraintName("fk_table_sessions_user_opened_by_user_id");

                    b.HasOne("Back.Models.User", "AssignedWaiter")
                        .WithMany()
                        .HasForeignKey("AssignedWaiterId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_table_sessions_user_assigned_waiter_id");

                    b.HasOne("Back.Models.Table", "Table")
                        .WithMany("Sessions")
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_table_sessions_tables_table_id");

                    b.Navigation("AssignedWaiter");

                    b.Navigation("ClosedByUser");

                    b.Navigation("OpenedByUser");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("Back.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Back.Models.Combo", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Back.Models.Coupon", b =>
                {
                    b.Navigation("Redemptions");
                });

            modelBuilder.Entity("Back.Models.Modifier", b =>
                {
                    b.Navigation("ProductModifiers");
                });

            modelBuilder.Entity("Back.Models.Order", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("KitchenTickets");

                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("Back.Models.Product", b =>
                {
                    b.Navigation("ProductModifiers");
                });

            modelBuilder.Entity("Back.Models.Table", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("Back.Models.TableSession", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
